apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: capstone-alert-rules
  namespace: capstone
  labels:
    release: prometheus
spec:
  groups:
    - name: pod-health.rules
      rules:
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[5m]) > 0.1
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Pod is restarting too frequently"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently (rate > 0.1 per 5 minutes)"

        - alert: PodNotReady
          expr: kube_pod_status_ready{condition="true"} == 0
          for: 3m
          labels:
            severity: critical
          annotations:
            summary: "Pod not ready"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not ready"

    - name: backend-errors.rules
      rules:
        - alert: HighBackendErrorRate
          expr: rate(http_requests_total{job="finch-backend", status=~"5.."}[5m]) > 1
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "High backend error rate"
            description: "More than 1 error per second on finch-backend"

    - name: redis-postgres.rules
      rules:
        - alert: RedisDown
          expr: up{job="redis-exporter"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Redis is down"
            description: "Redis exporter is not responding"

        - alert: PostgresDown
          expr: up{job="postgres-exporter"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "PostgreSQL is down"
            description: "PostgreSQL exporter is not responding"
